#!/bin/ash

echo && echo
echo "[1;36m""Porteus data not found.
You are maybe using an unsupported boot device (eg. SCSI or old PCMCIA).
Workaround: Copy the directory $FOLDER from your boot device to an IDE/SATA
disk, eg. to /mnt/sda1/porteus or C:\\porteus. Then try to boot again.
Make sure that your boot parameters (cheatcodes) are correct.
In case of booting over network - check if the driver for your NIC
is included in initrd image.

Now you can try to mount your device manually and locate *.sgn file

Example:
mkdir /tmp/sdb1
mount /dev/sdb1 /tmp/sdb1
ls /tmp/sdb1/porteus

Be aware that 'from=' cheatcode is no longer valid, check /boot/docs/cheatcodes.txt
for more information about new cheatcodes introduced in Porteus.

Here is the shell for you:""[0m"
ash </dev/console